pipelines:
    tags:
        'v*':
            - step:
                  name: Creating Docker image and pushing to Docker Hub
                  image: atlassian/default-image:2
                  services:
                      - docker
                  script:
                      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
                      - docker build -t keletes/$BITBUCKET_REPO_SLUG:latest .
                      - docker push keletes/$BITBUCKET_REPO_SLUG:latest
                      - docker tag keletes/$BITBUCKET_REPO_SLUG:latest keletes/$BITBUCKET_REPO_SLUG:$BITBUCKET_TAG
                      - docker push keletes/$BITBUCKET_REPO_SLUG:$BITBUCKET_TAG
                  caches:
                      - docker
                      - node
